module.exports = [
  {
    title: "Land of Coffee",
    category: "Trekking",
    G_location: "Chickmagaluru",
    Cost: 1284.56465,
    Photo: "https://source.unsplash.com/random/200x200?sig=2",
    Days: 10,
  },
  {
    title: "North Karnataka",
    category: "Heritage visit",
    G_location: "Bijapur",
    Cost: 1284.56465,
    Photo: "https://source.unsplash.com/random/200x200?sig=2",
    Days: 7,
  },
  {
    title: "Coastals of Karnataka",
    category: "Beach",
    G_location: "Udupi",
    Cost: 1284.56465,
    Photo: "https://source.unsplash.com/random/200x200?sig=2",
    Days: 7,
  },
  {
    title: "Around chickmagaluru",
    category: "Temples",
    G_location: "Sringeri",
    Cost: 1284.56465,
    Photo: "https://source.unsplash.com/random/200x200?sig=2",
    Days: 15,
  },
  {
    title: "Wildlife in karnataka",
    category: "Zoo and bird sanctuary",
    G_location: "Ballari",
    Cost: 1284.56465,
    Photo: "https://source.unsplash.com/random/200x200?sig=2",
    Days: 7,
  },
];
